Maior desafio que pensava! Mas vamos começar com só restrição de conf local!

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -7,11 +7,29 @@ STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.php$')
 
 # Run duster and rector only on staged PHP files
 if [ -n "$STAGED_FILES" ]; then
-  #echo "$STAGED_FILES" | xargs ./backend/vendor/bin/phpstan analyse --level=max
-  #if [ $? -ne 0 ]; then exit 1; fi
+  echo "$STAGED_FILES" | xargs ./backend/vendor/bin/phpstan analyse --level=max
+  if [ $? -ne 0 ]; then exit 1; fi
   
   echo "$STAGED_FILES" | xargs ./backend/vendor/bin/phpcbf --standard=PSR12
-  if [ $? -ne 0 ]; then exit 1; fi
+  PHPCBF_EXIT_CODE=$?
+
+  # If phpcbf fixed all issues (exit code 0), continue with the commit
+  if [ $PHPCBF_EXIT_CODE -eq 0 ]; then
+      echo "All issues fixed by phpcbf. Proceeding with commit."
+      exit 0
+  fi
+
+  # If phpcbf found issues that it couldn't fix (exit code 1), stop the commit
+  if [ $PHPCBF_EXIT_CODE -eq 1 ]; then
+      echo "phpcbf found issues that it couldn't fix. Stopping commit."
+      exit 1
+  fi
+
+  # If phpcbf encountered an error (exit code 2 or higher), stop the commit
+  if [ $PHPCBF_EXIT_CODE -ge 2 ]; then
+      echo "phpcbf encountered an error. Stopping commit."
+      exit 1
+  fi
 
   echo "$STAGED_FILES" | xargs ./backend/vendor/bin/duster fix
   if [ $? -ne 0 ]; then exit 1; fi
